openapi: 3.0.0
info:
  title: UTM Marketplace API
  description: API specification for a campus-wide marketplace app
  version: 1.0.0

servers:
  - url: https://api.utmmarketplace.com
    description: Production Server
  - url: http://localhost:5000
    description: Local Development Server

paths:
  /sign-up:
    post:
      summary: Sign up a new user
      description: Registers a new user using an email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "student@utoronto.ca"
                password:
                  type: string
                  format: password
                  example: "P@ssword123"
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 42
                  message:
                    type: string
                    example: "User registered successfully."
        "400":
          description: Bad Request - Invalid email or password format
        "409":
          description: Conflict - Email already in use
        "500":
          description: Internal Server Error

  /login:
    post:
      summary: Log in an existing user
      description: Authenticates a user using email and password. Returns a JWT token if valid credentials are provided.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "student@utoronto.ca"
                password:
                  type: string
                  format: password
                  example: "P@ssword123"
      responses:
        "200":
          description: Logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR..."
                  token_type:
                    type: string
                    example: "bearer"
        "401":
          description: Unauthorized - Invalid email or password
        "500":
          description: Internal Server Error

  /listings:
    get:
      summary: Retrieve all listings
      description: Fetches all product/service listings available in the marketplace.
      responses:
        "200":
          description: A list of marketplace listings
        "500":
          description: Internal Server Error
    post:
      summary: Create a new listing
      description: Adds a new product or service listing to the marketplace.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Gaming Laptop for sale"
                price:
                  type: number
                  format: float
                  example: 899.99
                description:
                  type: string
                  example: "Lightly used gaming laptop, great condition!"
      responses:
        "201":
          description: Listing created successfully
        "500":
          description: Internal Server Error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT